FROM ruby:2.5

# Install OS packages
RUN apt-get update && \
    apt-get install -y \
    git \
    nodejs

# Create application directory
RUN mkdir /app
WORKDIR /app

# Add app dependencies
ADD gems.rb ./
ADD gems.locked ./
RUN gem install bundler && bundle install

# Copy the application code
ADD . /app

# Expose port 8080 to the Docker host, so we can access it
# from the outside.
EXPOSE 8080

# Start puma
CMD bundle exec puma
